name: MaintenanceMode
version: 1.0
main: com.ula.mm.main
description: "Set your server on Maintenance Mode with this open source plugin."
author: Ula492

commands:
  mm:
    description: Shows commands for MaintenanceMode

permissions:
  mm.use:
    default: op
